### ISSUE TITLE
Script for fixing broken networks

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#139]
In some cases it can happen that one obtains a disconnected network due to a failed edge in the benchmarking process.

We would like to provide a script that benchmarking partners can run to add some additional edges to the network that would fix the network.

**Comment by jameseastwood** [comment]
This should be re-written to NOT use Konnektor, since installing that package into an existing environment could cause trouble.

**Comment by jameseastwood** [comment]
Zip the results folder
