### ISSUE TITLE
Create a data gathering script

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#149]
We need a script that gathers relevant information for subsequent analysis from the openfe team.

**Comment by hannahbaumann** [comment]
Diagram for the gathering script:
https://drive.google.com/file/d/1IqN5CPoqQcR5Y-HtEXOUUl8k5u5iU2AL/view

- taking each component here and working on each of them as small methods --> write quick unit tests that don't need the full input
