### ISSUE TITLE
Gathering script: Collect errored transformation info

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/IndustryBenchmarks2024#168]
We would like to collect information about errored edges to identify common failure modes, we might also see some force field parameterisation issues like missing BBCs or valence terms.

**Comment by hannahbaumann** [comment]
As discussed in this PR https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/179 we can't store the traceback. Is there a different way to collect some information of the failure or will we just store the number (and transformation scores) of the failed edges?

**Comment by hannahbaumann** [comment]
Should we have this as a question in the online form in case they want to report more information about specific failures?

**Comment by IAlibay** [comment]
> Should we have this as a question in the online form in case they want to report more information about specific failures?

I think I would agree with that, but we probably have to go in with low expectations - because not everyone is going to know what to look out for (we can work with individuals where necessary, but writing docs to suitably cover things is probably unlikely imho).

**Comment by IAlibay** [comment]
This is done as far as I'm aware.
