### ISSUE TITLE
`Documentation`: FAQ 

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/IndustryBenchmarks2024#174]
It might be a good idea to have an FAQ section where we can direct people regarding issues like fixing broken networks, as currently information is explained once in the public benchmark sections and then repeated in the private section this would also make docs changes easier if the information was all in one location.

**Comment by IAlibay** [comment]
We have an FAQ page but it's in the wrong llocation / needs more info: https://industrybenchmarks2024.readthedocs.io/en/latest/private/prep_and_debug.html
