### ISSUE TITLE
Gathering: replace ligand names with random strings

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#190]
Some of our partners have run the private datasets with internal ligand names. We will need to replace the ligand names in the gathering script and also provide a table of private to public names for the partners.

**Comment by jthorton** [comment]
Is it safe to use the gufe key of the ligand? Or should we use a random string like a, b, c ?

**Comment by IAlibay** [comment]
I think we will need to use something more human accessible - the partners will need to manually provide assay data and as part of this will need to match the new names with the old ones, so long gufe keys might be a lot of work.
