### ISSUE TITLE
Create template for experimental results CSV

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#207]
We will want to have our partners submit their experimental results in a set manner.

We propose a CSV file with the following fields:
  - Ligand Name
  - Affinity (nm)
  - Affinity Error (nm)
  - Annotation

Note 1: Affinity error should probably be set to something like -1 when unavailable.
Note 2: Annotation should be for things like "assay changed here" or ">1000", etc...

**Comment by jthorton** [comment]
Is the plan to write this template into the docs, I imagine most will be using scripts to generate the data so an actual CSV with this header might not be super helpful?

**Comment by IAlibay** [comment]
Yeah, docs sound good - if we can get an example Zenodo submission with the csv that would be useful.
