### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#209]
The readme is out of date, let's update it!

**Comment by jthorton** [comment]
Do we just want to point to the relevant part of the docs for each section rather than having to keep the two in sync?

**Comment by IAlibay** [comment]
> Do we just want to point to the relevant part of the docs for each section rather than having to keep the two in sync?

Yeah that'd be great! The readme is mostly a leftover of a time when we didn't have docs 😅
