### ISSUE TITLE
Public benchmarks: create a benchmark analysis plan

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#33]
We should create a plan for what analyses do we want to do on the benchmark results, i.e. draft a general overview of the analysis section of a paper.

**Comment by jameseastwood** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OpenFE-6615a0133899140ef86163db/issues/OpenFreeEnergy/IndustryBenchmarks2024/33?planning-poker) with Zenhub @hannahbaumann @IAlibay @mikemhenry @RiesBen

**Comment by jameseastwood** [comment]
https://docs.google.com/document/d/1FXkIqz7sYVwK81Qe5KU2lGKZz1zfpHuUr_C7KwBgZqw/edit?usp=sharing

**Comment by jameseastwood** [comment]
Please read and comment on the document above @IAlibay @mikemhenry

**Comment by jameseastwood** [comment]
Next steps:

- [ ] 1. Incorporate comments
- [ ] 2. Clean up questions
- [ ] 3. Remove example figures
- [ ] 4. Send to board in meeting follow-up to solicit more comments

**Comment by jameseastwood** [comment]
Send this out in advance of the August not-a-board meeting
