### ISSUE TITLE
Create a post-simulation cleanup script

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#48]
Mike has been working on a post-simulation script which:
- Finds all the input JSON files
- Checks if the simulation is complete
- Does something

Can modify the script to safely run multiple times & post-process simulations.

TODO:
- [x] Create necessary script to downsample files
- [x] Validate the post-simulation cleanup script

**Comment by mikemhenry** [comment]
resolved by #83
