### ISSUE TITLE
QA installation instructions

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#51]
Follow up from #48

Once we have instructions in place, we need to QA the instructions, building an environment from scratch using the conda-lock file and the single file installer.

Ideally someone that isn't involved in the process like @jameseastwood

**Comment by IAlibay** [comment]
@RiesBen could you try out installing the single file installer and the conda-lock file on the BI clusters.

**Comment by RiesBen** [comment]
@IAlibay  a problem, that I encountered here:
I have a living conda env in on my cluster account, therefore I want to have a non-invasive way how I could use the installed openforge env. But I don't know how to do that, do you? (non-invasive, means not overwriting the bashrc conda init)

**Comment by IAlibay** [comment]
@mikemhenry can you weigh in on this?

**Comment by RiesBen** [comment]
will share an output file later.

many errors:
` TypeError: Can't instantiate abstract class BadMapper with abstract methods _defaults, _from_dict, _to_dict`
`pydantic.v1.error_wrappers.ValidationError: 1 validation error for OpenMMSystemGeneratorFFSettings`
`- AttributeError: 'list' object has no attribute 'values'`
`AttributeError: 'OpenMMSystemGeneratorFFSettings' object has no attribute 'remove_com'`

**Comment by jameseastwood** [comment]
I'm working from this, right? https://industrybenchmarks2024.readthedocs.io/en/latest/installation.html

**Comment by jameseastwood** [comment]
minor point: `$ conda-lock install -n openfe conda-lock-openfe.yml` doesn't run as-is because the actual filename includes the version number

**Comment by jameseastwood** [comment]
I find it a little confusing where/how the single file installer creates its conda environment, but that's fine. It works.

**Comment by hannahbaumann** [comment]
> minor point: `$ conda-lock install -n openfe conda-lock-openfe.yml` doesn't run as-is because the actual filename includes the version number

I updated the file names (also for the single file installer) in this PR: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/71
