### ISSUE TITLE
QA preparation instructions

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#52]
We should QA the preparation instructions and make sure that they make sense end-to-end.

Ideally we synchronously run through preparing a system like TYK2.

- [ ] Link install instructions for "Phase 0"
- [ ] Fix formatting on compute requirements section
- [ ] Add warning to wait on phase two until we QA inputs

**Comment by mikemhenry** [comment]
![image](https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/assets/11765982/7a2a5a4a-8b16-4424-bcc9-f29477557f5f)
@IAlibay formatting jumbled here
