### ISSUE TITLE
Work out how we handle triplicate simulations

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#62]
The OpenFE default is to run all triplicates in one go. This may be ok for standard transformations, but for net charge transformations this could lead to very large walltime needs.

Should we split the simulation in 3 sets of 1 repeat instead?

**Comment by IAlibay** [comment]
@mikemhenry @RiesBen @hannahbaumann as discussed in today's call, please put together your ideas on how you would like this to go and/or how you have been doing this until now.

This includes, but is not limited to, any scripts you have been using (e.g. Mike's 1.0 QA script).

**Comment by hannahbaumann** [comment]
I had forgotten that Mike actually already did what I think might be best:
```
results_p38_0/edge_AB_complex
results_p38_0/edge_AB_complex.json
results_p38_0/edge_AB_solvent
results_p38_0/edge_AB_solvent.json
results_p38_0/edge_CD_complex
```
-----
```
results_p38_1/edge_AB_complex
results_p38_1/edge_AB_complex.json
results_p38_1/edge_AB_solvent
results_p38_1/edge_AB_solvent.json
results_p38_1/edge_CD_complex
```
-----
```
results_p38_2/edge_AB_complex
results_p38_2/edge_AB_complex.json
results_p38_2/edge_AB_solvent
results_p38_2/edge_AB_solvent.json
results_p38_2/edge_CD_complex
```

**Comment by hannahbaumann** [comment]
Are there other options?
