### ISSUE TITLE
Add reviewer instructions

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#7]
We need a set of instructions for reviewers of submitted inputs

**Comment by hannahbaumann** [comment]
Items for a checklist:

- directory structure and file names as in the template
- filled in system preparation details in the PREPARATION_DETAILS.md file
    - preparation details make sense and are sufficiently detailed to be able to reproduce it
- added a PDB file with the protein named protein.pdb
    - removed any cofactors from the PDB file and placed them in cofactors.sdf
    - kept cystallographic waters and metals in the PDB file
    - amino acids have the same protonation states as in the original structure prepped by Ross et al.
- copied over the ligands SDF file to a file named ligands.sdf and removed any duplicate binding modes or protonation states, keeping the more favorable state

**Comment by IAlibay** [comment]
We should check that there are no likely missing disulfide bridges:

1. Check if there are SG atoms that are close to each other ( within 2.5 A of each other)
2. Check that those SG atoms are not connected to a hydrogen
3. Encourage the writing of a connect record for each bond (I checked and it's not really necessary for us, but it does help).

**Comment by IAlibay** [comment]
Run the protein check script
  - make sure that any differences in chain termini are down to reasonably capping procedures
