### ISSUE TITLE
industry-benchmarking-layout

### ISSUE THREAD

**Issue by RiesBen** [OpenFreeEnergy/IndustryBenchmarks2024#72]
Hi, I think it would be great if our folder structure follows this here:
https://docs.openfree.energy/en/stable/tutorials/rbfe_cli_tutorial.html

in my understanding the final folder structure, after full execution should look like this:

some_benchmark_folder

--network_setup
-----ligand_network.graphml
-----alchemical_network.json
-----transformations
-------*jsons

--results
----fun1
------shared_*
--------nc
-----fun1.json
----fun2
------shared_
--------*nc
-----fun2.json
---- ...

--final_results.tsv

**Comment by IAlibay** [comment]
@RiesBen 

> -----ligand_*json

Sorry for the silly question, but what is this? The alchemical network?

> --results

I think the way we wanted to go was:

-- network_setup
  - ligand_network.graphml
  - alchemical_network.json
  --transformations
  --- transformation JSONs
  -- results_0
    - replica 0 results for each transformation
  -- results_1
    - replica 1 results for each transformation
  -- results_2
    - replica 2 results for each transformation

Does that match what you envision?

**Comment by hannahbaumann** [comment]
I don't think I would put the results under `network_setup` since that seems confusing to me, but may just be me!

**Comment by IAlibay** [comment]
> I don't think I would put the results under `network_setup` since that seems confusing to me, but may just be me!

Yes sorry! That should be separate

**Comment by RiesBen** [comment]
@IAlibay - file name of ligand_*json: ja my bad, I corrected that in the initial post

**Comment by IAlibay** [comment]
I've opened PR #76 with the aim of fixing this
