### ISSUE TITLE
Update instructions to point to using conda-lock file with micromamba

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/IndustryBenchmarks2024#87]
In some cases, some folks might not be able to use conda-lock due to the way in which conda is being blocked. In those cases, it is possible to use micromamba instead with the conda-lock.yml file. Additional instructions should be provided for this.

**Comment by mikemhenry** [comment]
Resolved by https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/pull/86
